version: '3'

services:
  tarantool:
    image: tarantool/tarantool
    ports:
      - "3301:3301"
    expose:
      - 3301
    volumes:
      - ./tarantool/tarantool.lua:/etc/tarantool.lua
    command: tarantool /etc/tarantool.lua
    networks:
      - my-network

  fastapi:
    build: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - tarantool
    restart: always
    environment:
      - TARANTOOL_HOST=tarantool
    networks:
      - my-network

networks:
  my-network:
    driver: bridge